# Generated by Django 4.2.30 on 2026-05-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
