# Generated by Django 4.2.30 on 2026-05-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0002_page_is_favorite"),
        ("notebooks", "0002_pageusershare"),
    ]

    operations = []
