# Generated by Django 4.2.30 on 2026-05-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0003_merge_0002_page_is_favorite_0002_pageusershare"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_folders",
                        to="notebooks.notebook",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
                "unique_together": {("notebook", "name")},
            },
        ),
        migrations.AddField(
            model_name="page",
            name="topic_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pages",
                to="notebooks.topicfolder",
            ),
        ),
    ]
