import client from './client'

export const getPages = (notebookId) => client.get(`/notebooks/${notebookId}/pages/`)
export const createPage = (notebookId, data) => client.post(`/notebooks/${notebookId}/pages/`, data)
export const getPage = (id) => client.get(`/pages/${id}/`)
export const updatePage = (id, data) => client.patch(`/pages/${id}/`, data)
export const deletePage = (id) => client.delete(`/pages/${id}/`)
export const createShare = (id) => client.post(`/pages/${id}/share/`)
export const revokeShare = (id) => client.delete(`/pages/${id}/share/`)
export const getSharedPage = (token) => client.get(`/shared/${token}/`)
export const getFavoritePages = () => client.get('/pages/favorites/')
export const toggleFavoritePage = (id, isFavorite) => client.patch(`/pages/${id}/`, { is_favorite: isFavorite })
export const getSharedUsers = (id) => client.get(`/pages/${id}/share/users/`)
export const addSharedUser = (id, username) => client.post(`/pages/${id}/share/users/`, { username })
export const removeSharedUser = (id, userId) => client.delete(`/pages/${id}/share/users/${userId}/`)
export const getSharedWithMe = () => client.get('/shared-with-me/')
export const aiEditPage = (id, text, action) => client.post(`/pages/${id}/ai-edit/`, { text, action })
export const importWebpage = (notebookId, data) => client.post(`/notebooks/${notebookId}/import-webpage/`, data)
