# Generated by Django 5.2.13 on 2026-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-is_favorite", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="page",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
